//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS.StaffManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.Guid> OrganizationID { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public byte[] HashPassword { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IslockedOut { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual RoleType RoleType { get; set; }
    }
}
